### ISSUE TITLE
0.4.0: Error running FreezedGenerator: ... but freezed has nothing to generate"

### ISSUE THREAD

**Issue by jonasbark** [rrousselGit/freezed#40]
File:
```dart
import 'package:freezed_annotation/freezed_annotation.dart';
part 'second_state.freezed.dart';
part 'second_state.g.dart';

@freezed
abstract class SecondState with _$SecondState {
  const factory SecondState({
    @JsonKey(ignore: true, nullable: true) String dateTime,
    @JsonKey(ignore: true, nullable: true) String uuid,
  }) = _SecondState;

  const factory SecondState.fromJson(Map<String, dynamic> json) => _$SecondStateFromJson(json);
}
```
Error:
```
[SEVERE] freezed:freezed on lib/state/second_state/second_state.dart:
Error running FreezedGenerator
Marked SecondState with @freezed, but freezed has nothing to generate
package:example/state/second_state/second_state.dart:6:16
  ╷
6 │ abstract class SecondState with _$SecondState {
  │                ^^^^^^^^^^^
  ╵
```
Did I forget something? All other state files fail as well (so it's not the fact that both fields have ignore: true at JsonKey)

**Comment by rrousselGit** [comment]
That's a regression.

It happens because the constructor is defined on multiple lines. If you format it in a single line, that should work for now.

I'll fix it asap

**Comment by rrousselGit** [comment]
The fix is released as part of 0.5.0

**Comment by alekline** [comment]
Thank you for the hard work put into this. 

A similar problem is still happening in version 0.10.6 - If you have comments in between the variables, and these comments have parenthesis, you MUST close the parenthesis or freezed won't be able to generate the files:

`@freezed
abstract class MyClass with _$MyClass {
  const factory MyClass({
    @required String myStr1,
    @required bool myBool1,

    /// These comments Cause problems only when I (don't close the parenthesis
    // It doesn't matter if you have two or three bar comments, or single quotes, as long as you (close the parenthesis)
    @required String mySpecialStr,
  }) = _MyClass;

}
`

So I guess good grammar is always a must :-)

**Comment by DmitryVoronko** [comment]
Looks like the same issue

```dart
import 'package:freezed_annotation/freezed_annotation.dart';

part 'device_config.freezed.dart';

@freezed
abstract class DeviceConfig with _$DeviceConfig {
  const factory DeviceConfig({
    @required String systemName,
    @required String systemVersion,
    @required String model,
  }) = _DeviceConfig
}
```

```yaml
environment:
  sdk: '>=2.10.0 <3.0.0'

dependencies:
  freezed_annotation: 0.12.0


dev_dependencies:
  freezed: 0.12.2
  build_runner: 1.10.2
```

```cli
flutter pub run build_runner build --delete-conflicting-outputs

[INFO] Generating build script...
[INFO] Generating build script completed, took 383ms

[INFO] Creating build script snapshot......
[INFO] Creating build script snapshot... completed, took 11.9s

[INFO] Initializing inputs
[INFO] Building new asset graph...
[INFO] Building new asset graph completed, took 624ms

[INFO] Checking for unexpected pre-existing outputs....
[INFO] Checking for unexpected pre-existing outputs. completed, took 1ms

[INFO] Running build...
[INFO] Generating SDK summary...
[INFO] 3.8s elapsed, 0/4 actions completed.
[INFO] Generating SDK summary completed, took 3.8s

[WARNING] freezed:freezed on lib/device_config.dart:
Error Marked DeviceConfig with @freezed, but freezed has nothing to generate
package:freezed_has_nothing_to_generate_reproduce/device_config.dart:6:16
  ╷
6 │ abstract class DeviceConfig with _$DeviceConfig {
  │                ^^^^^^^^^^^^
  ╵
[WARNING] freezed:freezed on lib/device_config.dart:
#0      FreezedGenerator.parseElement (package:freezed/src/freezed_generator.dart:242:7)
#1      ParserGenerator.generate (package:freezed/src/parse_generator.dart:29:22)
#2      _generate (package:source_gen/src/builder.dart:303:33)
<asynchronous suspension>
#3      _Builder._generateForLibrary (package:source_gen/src/builder.dart:79:15)
#4      _Builder.build (package:source_gen/src/builder.dart:71:11)
<asynchronous suspension>
#5      runBuilder.buildForInput (package:build/src/generate/run_builder.dart:55:21)
#6      MappedListIterable.elementAt (dart:_internal/iterable.dart:417:31)
#7      ListIterator.moveNext (dart:_internal/iterable.dart:343:26)
#8      Future.wait (dart:async/future.dart:406:26)
#9      runBuilder.<anonymous closure> (package:build/src/generate/run_builder.dart:61:36)
#10     _rootRun (dart:async/zone.dart:1190:13)
#11     _CustomZone.run (dart:async/zone.dart:1093:19)
#12     _runZoned (dart:async/zone.dart:1630:10)
#13     runZonedGuarded (dart:async/zone.dart:1618:12)
#14     runZoned (dart:async/zone.dart:1547:12)
#15     scopeLogAsync (package:build/src/builder/logging.dart:26:3)
#16     runBuilder (package:build/src/generate/run_builder.dart:61:9)
#17     _SingleBuild._runForInput.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:build_runner_core/src/generate/build_impl.dart:485:19)
#18     _NoOpBuilderActionTracker.trackStage (package:build_runner_core/src/generate/performance_tracker.dart:302:15)
#19     _SingleBuild._runForInput.<anonymous closure>.<anonymous closure> (package:build_runner_core/src/generate/build_impl.dart:483:23)
<asynchronous suspension>
#20     _SingleBuild._runForInput.<anonymous closure>.<anonymous closure> (package:build_runner_core/src/generate/build_impl.dart)
#21     NoOpTimeTracker.track (package:timing/src/timing.dart:222:44)
#22     _SingleBuild._runForInput.<anonymous closure> (package:build_runner_core/src/generate/build_impl.dart:440:22)
#23     Pool.withResource (package:pool/pool.dart:127:28)
<asynchronous suspension>
#24     _SingleBuild._runForInput (package:build_runner_core/src/generate/build_impl.dart:436:17)
#25     _SingleBuild._runBuilder.<anonymous closure> (package:build_runner_core/src/generate/build_impl.dart:374:38)
#26     MappedIterator.moveNext (dart:_internal/iterable.dart:392:20)
#27     Future.wait (dart:async/future.dart:406:26)
#28     _SingleBuild._runBuilder (package:build_runner_core/src/generate/build_impl.dart:373:36)
#29     _SingleBuild._runPhases.<anonymous closure>.<anonymous closure> (package:build_runner_core/src/generate/build_impl.dart:319:20)
#30     _rootRunUnary (dart:async/zone.dart:1198:47)
#31     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#32     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
#33     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
#34     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
#35     Future._completeWithValue (dart:async/future_impl.dart:529:5)
#36     _AsyncAwaitCompleter.complete (dart:async-patch/async_patch.dart:40:15)
#37     _completeOnAsyncReturn (dart:async-patch/async_patch.dart:311:13)
#38     _SingleBuild._matchingPrimaryInputs (package:build_runner_core/src/generate/build_impl.dart)
#39     _rootRunUnary (dart:async/zone.dart:1198:47)
#40     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#41     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
#42     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
#43     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
#44     Future._completeWithValue (dart:async/future_impl.dart:529:5)
#45     Future.wait.<anonymous closure> (dart:async/future.dart:414:23)
#46     _rootRunUnary (dart:async/zone.dart:1198:47)
#47     _CustomZone.runUnary (dart:async/zone.dart:1100:19)
#48     _FutureListener.handleValue (dart:async/future_impl.dart:143:18)
#49     Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:696:45)
#50     Future._propagateToListeners (dart:async/future_impl.dart:725:32)
#51     Future._completeWithValue (dart:async/future_impl.dart:529:5)
#52     Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:567:7)
#53     _rootRun (dart:async/zone.dart:1190:13)
#54     _CustomZone.run (dart:async/zone.dart:1093:19)
#55     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
#56     _CustomZone.bindCallbackGuarded.<anonymous closure> (dart:async/zone.dart:1037:23)
#57     _microtaskLoop (dart:async/schedule_microtask.dart:41:21)
#58     _startMicrotaskLoop (dart:async/schedule_microtask.dart:50:5)
#59     _runPendingImmediateCallback (dart:isolate-patch/isolate_patch.dart:118:13)
#60     _RawReceivePortImpl._handleMessage (dart:isolate-patch/isolate_patch.dart:169:5)

[SEVERE] freezed:freezed on lib/device_config.dart:

Marked DeviceConfig with @freezed, but freezed has nothing to generate
package:freezed_has_nothing_to_generate_reproduce/device_config.dart:6:16
  ╷
6 │ abstract class DeviceConfig with _$DeviceConfig {
  │                ^^^^^^^^^^^^
  ╵
[INFO] Running build completed, took 4.6s

[INFO] Caching finalized dependency graph...
[INFO] Caching finalized dependency graph completed, took 31ms

[SEVERE] Failed after 4.6s
pub finished with exit code 1
```
