### ISSUE TITLE
Allow mutable fields if the constructor is not `const`

### ISSUE THREAD

**Issue by eliezedeck** [rrousselGit/freezed#598]
**Is your feature request related to a problem? Please describe.**
It's not related to any issues I believe. However, right now, it is not possible to have a **custom mutable field** even though the constructor is not const, meaning that it is not necessary for all fields to be final, and consequently, a mutation should be possible. This would be a very conscious choice, as would be a `const` constructor for immutable objects.

**Describe the solution you'd like**
Nothing fancy, just allow the mutable fields when the constructor is not `const`

**Describe alternatives you've considered**
I have not found any alternatives while using freezed.

**Additional context**
It is always a good thing to have flexibility at hand. What I'm suggesting is still well within what's logical in Dart, and using freezed, this freedom/flexibility is gone right now. That limits what's possible when using freezed, and may even hinder productivity, whereas productivity was the initial goal to adopt freezed in the first place.

With that said, I'm no Dart expert and I would gladly welcome any suggestion that would render my suggestion obsolete, while restoring the desired Dart possibilities.

**Comment by rrousselGit** [comment]
Done as part of the next release

**Comment by eliezedeck** [comment]
@rrouselGit nope! I still get the same behavior as before. I have just upgraded everything to the latest version, and I still got:

```
Classes decorated with @freezed cannot have mutable properties
```

**Comment by rrousselGit** [comment]
You need to use `@unfreezed`

**Comment by eliezedeck** [comment]
Yes, I am already using `@unfreezed`

**Comment by rrousselGit** [comment]
Can you clarify then, with a complete example?

**Comment by eliezedeck** [comment]
Sure, take for instance, this `test.dart` class:

```dart
import 'package:freezed_annotation/freezed_annotation.dart';

part 'test.freezed.dart';
part 'test.g.dart';

@unfreezed
class NonConstantClass with _$NonConstantClass {
  NonConstantClass._();

  @JsonKey(ignore: true)
  String? tempField;

  factory NonConstantClass({
    required String name,
    required String createdBy,
    required String createdByMemberId,
  }) = _NonConstantClass;

  factory NonConstantClass.fromJson(Map<String, dynamic> json) => _$NonConstantClassFromJson(json);
}
```

I would get this error, even though this is clearly a non-const class, and the `@unfreezed` notation is used:

```
Classes decorated with @freezed cannot have mutable properties
package:xxxx/test.dart:11:11
   ╷
11 │   String? tempField;
   │           ^^^^^^^^^
   ╵
```

**Comment by rrousselGit** [comment]
Ah, well the syntax is supposed to be:

```dart
@unfreezed
class NonConstantClass with _$NonConstantClass {
  NonConstantClass._();


  factory NonConstantClass({
    required String name,
    required String createdBy,
    required String createdByMemberId,
    @JsonKey(ignore: true)
    String? tempField;
  }) = _NonConstantClass;

  factory NonConstantClass.fromJson(Map<String, dynamic> json) => _$NonConstantClassFromJson(json);
}
```


But I'll look into it

**Comment by eliezedeck** [comment]
Ah, ok. However, I want the field to be completely ignore by Freezed, thereby avoiding all possible overhead since it's going to be a temporary field. Is it case in your example?

**Comment by eliezedeck** [comment]
There is one important use case where a temporary private field is needed, something like `String? _tempField` but that is not allowed as constructor parameter, the name **cannot start with underscore**.

So, I think the field being **outside** the `factory ClassName(...)...` is important. With that being said, I manually disable the check in the file `lib/src/freezed_generator.dart:187` from the **freezed** package. I hope this would help in this issue:

```dart
  void _assertValidFieldUsage(
    FieldElement field, {
    required bool shouldUseExtends,
  }) {
    if (field.isStatic) return;

    // if (field.setter != null) {
    //   throw InvalidGenerationSourceError(
    //     'Classes decorated with @freezed cannot have mutable properties',
    //     element: field,
    //   );
    // }

    // ...
  }
```

Another thing I have noticed: build runner succeeds even if the class is decorated with `@freezed` instead of the recommended `@unfreezed`. So, I'm not sure if it makes a difference now.

**Comment by davidpanic** [comment]
We'd like to have this as well, our use case is some computed variables that we want to have generated in the constructor instead of being passed as variables. It's easy enough to add a body to `ClassName._()` but freezed complains about our late final fields.

Here's an example:

```dart
@freezed
class ExacmpleClass with _$ExacmpleClass {
  late final ComputedData exampleComputedField;

  factory ExacmpleClass({
    required final List<Whatever> exampleValues,
  }) = _ExacmpleClass;

  ExacmpleClass._() {
    exampleComputedField = expensiveOperation(exampleValues);
  }

  factory ExacmpleClass.fromJson(Map<String, dynamic> json) => _$ExacmpleClassFromJson(json);
}
```

This throws the following exception:

```
Classes decorated with @freezed cannot have mutable properties
package:[REDACTED]/filename.dart:lineN:lineColumn
   ╷
N  │   late final ComputedData exampleComputedField;
   │                           ^^^^^^^^^^^^^^^^^^^^
   ╵
```

**Comment by eliezedeck** [comment]
Hey @rrousselGit, I came back to the old project that used *freezed*. I have upgraded to the latest version, and got hit by this issue again. I get that you're probably busy with something more interesting, but do you think this could be solved anytime soon?
